services:
  backend:
    image: kwaneon/shoppingmall-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/project
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=qwe123
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    image: kwaneon/shoppingmall-frontend:latest
    ports:
      - "3000:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qwe123
      - MYSQL_DATABASE=project
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: